Issue #21: Add context-specific escaper helpers
zendframework/zend-expressive-platesrenderer pull request #22
Opened 2017-05-17 09:13 UTC by robopuff

2017-05-30 15:27 UTC, weierophinney requested changes
I've noted that we need to be able to specify the encoding as an optional feature. That would likely also require a factory for the extension, that would pull the encoding from configuration. That factory should be registered in the `ConfigProvider`.

Finally, this does not register the extension by default. I'm thinking it should, as an added feature of this bridge. As such, you'd need to update the `PlatesEngineFactory` to do so. Alternately, document that the extension exists, and demonstrate how to register it (via the `plates.extensions` configuration array, which allows specifying service names of extensions).

2017-05-30 15:27 UTC, weierophinney commented on src/Extension/EscaperExtension.php
> +        $escaper = new Escaper();
We should likely allow providing an encoding to use with the escaper. While the default of UTF-8 is fine, being able to specify another is something we definitely want within a template engine.

That could be done via a constructor parameter.

2017-06-01 07:25 UTC, robopuff commented on src/Extension/EscaperExtension.php
> +        $escaper = new Escaper();
You think that user should be able to provide a encoding in plates views as well?
For example: `escapeHtml($string, $encoding=null)`

2017-08-12 13:51 UTC, geerteltink approved these changes

2017-11-01 20:57 UTC, weierophinney approved these changes
The only other change I would make is to register the escaper extension in the `ConfigProvider` by default; I can do that on merge, though.

Nice work!

2017-11-01 21:20 UTC, weierophinney commented
Thanks, @robopuff; merged to develop for release with 1.4.0.

2017-11-01 21:20 UTC, closed without merging